logging:
  level:
    org.springframework.security: TRACE
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
server:
  context-path: /uaa
  port: 5000

spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: webshop
      port: 27017
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current