server:
  port: 10100
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/webshop
    username: shop
    password: shop
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate