logging:
  level:
    org.springframework.security: TRACE
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
server:
  port: 10200
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/webshop
    username: shop
    password: shop
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://auth-service:5000/uaa/users/current