#logging:
#  level:
#    org.springframework.security: TRACE
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000
server:
  port: 10300
security:
  oauth2:
    client:
      clientId: product-category-composite-service
      clientSecret: Welcome1
      accessTokenUri: http://user-core-service:9876/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      token-info-uri: http://user-core-service:9876/oauth/check_token
      user-info-uri: http://user-core-service:9876/current
